name: ✨ Feature Request
description: Propose a new feature or enhancement
title: "[Feature] "
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a [user type], I need [capability] so that [benefit]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe the desired functionality...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Mockups, references, related issues, etc.
      placeholder: Links, screenshots, or other relevant information...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        *Made with `✨ Feature Request` template*
